### ISSUE TITLE
Publish on Maven Central

### ISSUE THREAD

**Issue by DevSrSouza** [eduramiba/webcam-capture-driver-native#15]

**Comment by xian** [comment]
Any blockers to doing this? We'd love to use in https://github.com/baaahs/sparklemotion/pull/542. Thanks much for the driver! cc/ @kcking

**Comment by eduramiba** [comment]
@xian I plan to deploy this soon to maven central :)

**Comment by eduramiba** [comment]
This is now available in maven central.
See https://github.com/eduramiba/webcam-capture-driver-native#how-to-use
