### ISSUE TITLE
Publish artifacts to maven central

### ISSUE THREAD

**Issue by xian** [eduramiba/webcam-capture-driver-native#17]
Hey @eduramiba, thanks much for this! Any chance of getting artifacts published to maven central? We're using the drivers in [Sparkle Motion](https://github.com/baaahs/sparklemotion). Thanks!

**Comment by eduramiba** [comment]
This is now available in maven central.
See https://github.com/eduramiba/webcam-capture-driver-native#how-to-use

**Comment by xian** [comment]
Thank you so much Eduardo!
