### ISSUE TITLE
ERROR c.g.e.w.d.c.CaptureManagerDriver - Unexpected error listing video devices

### ISSUE THREAD

**Issue by i-make-robots** [eduramiba/webcam-capture-driver-native#18]
Java 21
IntelliJ IDEA 2023.2.5
com.github.sarxos:webcam-capture:0.3.12
this library v1.0.0

README documentation does not mention modules.  Workaround is to add `requires io.github.eduramiba.webcamcapture;`

Running the application as recommended, I get 
```
14:38:26.220 [main] DEBUG com.github.sarxos.webcam.Webcam - Setting new capture driver com.github.eduramiba.webcamcapture.drivers.NativeDriver@4e096385
14:38:26.239 [webcam-discovery-service] ERROR c.g.e.w.d.c.CaptureManagerDriver - Unexpected error listing video devices
java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\me\Documents\GitHub\myApp\CaptureManager.dll
14:38:26.241 [main] INFO  c.g.s.webcam.WebcamDiscoveryService - Discovery will not run - driver NativeDriver does not support this feature
```

I believe it's looking in the wrong place for the native driver.

**Comment by eduramiba** [comment]
Hi, take into account that you need to manually copy the correct DLLs where your application will be run as explained in the readme.
They are in https://github.com/eduramiba/webcam-capture-driver-native/tree/master/natives

For Mac, they are bundled in the jars

**Comment by i-make-robots** [comment]
Uh... where in https://github.com/eduramiba/webcam-capture-driver-native/blob/master/README.md does it mention copying DLLs?  Coz I read it and it's mostly one example for JavaFX that should probably be in a separate file.

**Comment by eduramiba** [comment]
I just released version `1.1.0`, which uses a different backend for native camera access in Windows. Can you try to update?

**Comment by i-make-robots** [comment]
How would I tell `com.github.sarxos:webcam-capture:0.3.12` to use the updated version?  Ah:
```
		<dependency>
			<groupId>io.github.eduramiba</groupId>
			<artifactId>webcam-capture-driver-native</artifactId>
			<version>1.1.0</version>
		</dependency>
```

**Comment by eduramiba** [comment]
No code changes are required, only updating your maven dependency

**Comment by i-make-robots** [comment]
Welp.... I'm not sure if it ran but it didn't crash?  Oddly I don't find the "requires" line from the OP in any of my code bases.
