### ISSUE TITLE
Open multiple webcam

### ISSUE THREAD

**Issue by pacioc193** [eduramiba/webcam-capture-driver-native#2]
First of all great library.

I've problem open multiple webcam. Untill 2 webcam everythings is fine... i need to open 6.
Error is the following : 

Exception in thread "main" com.github.sarxos.webcam.WebcamLockException: Webcam USB has already been locked

When no use your driver everythings is working well...

Any ideas?

**Comment by eduramiba** [comment]
Not sure, can you share your code?
Make sure to properly open/close different cameras and not open a same camera twice at the same time.

**Comment by pacioc193** [comment]
![image](https://user-images.githubusercontent.com/3874577/145606012-100c474d-e77a-4394-bb84-ecaba9716133.png)
USB Id :
![image](https://user-images.githubusercontent.com/3874577/145606060-379da47b-32af-4179-b762-f340924bd07c.png)

Problem could be fixed removing manually the lock by adding :

![image](https://user-images.githubusercontent.com/3874577/145606453-2883804c-2251-4444-9b3d-864f6430fe42.png)

**Comment by eduramiba** [comment]
Great, thanks, I dit not know about this lock before and find it unnecessary. Will add the lock disable to the example.
