### ISSUE TITLE
Webcam is not showing any preview nor the webcam is opening

### ISSUE THREAD

**Issue by shadowwalkersteam** [eduramiba/webcam-capture-driver-native#6]
I'm getting issue with this library, the webcam is not opening nor I see any preview on the UI. Below are the debug logs. 

`INFO_LEVEL: ***** CAPTUREMANAGER SDK 1.19.1 Freeware - Sep  4 2021 (Author: Evgeny Pereguda) *****
INFO_LEVEL: MediaFoundationManager: Media Foundation is initialized!!!
INFO_LEVEL: DMOManager: DMO is initialized!!!
2766 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse source - start
2778 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse stream descriptor - start
2780 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - start
2799 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - correct - subtype = MFAudioFormat_Float
2813 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse stream descriptor - ok
2814 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse source - ok
2814 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse source - start
2815 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse stream descriptor - start
2815 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - start
2817 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - correct - subtype = MFVideoFormat_YUY2
2841 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - start
2843 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - correct - subtype = MFVideoFormat_YUY2
2843 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - start
2844 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - correct - subtype = MFVideoFormat_YUY2
2844 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse stream descriptor - ok
2845 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse source - ok
2845 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse source - start
2846 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse stream descriptor - start
2846 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - start
2847 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - correct - subtype = MFVideoFormat_ARGB32
2847 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - start
2848 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - correct - subtype = MFVideoFormat_ARGB32
2848 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - start
2849 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - correct - subtype = MFVideoFormat_ARGB32
2849 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - start
2850 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - correct - subtype = MFVideoFormat_ARGB32
2850 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - start
2852 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - correct - subtype = MFVideoFormat_ARGB32
2852 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - start
2853 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - correct - subtype = MFVideoFormat_ARGB32
2853 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - start
2854 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - correct - subtype = MFVideoFormat_ARGB32
2855 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse stream descriptor - ok
2855 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse source - ok
2856 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse source - start
2857 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse stream descriptor - start
2857 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - start
2857 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse media type - correct - subtype = MFAudioFormat_Float
2858 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse stream descriptor - ok
2858 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse source - ok
2858 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Premature end of XML stream at root. Event type = 257
2864 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - start
2865 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - start
2871 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - ok
2871 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - ok
2871 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - start
2871 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - start
2872 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - ok
2872 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - ok
2872 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - start
2873 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - start
2873 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - ok
2873 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - ok
2874 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - start
2874 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - start
2875 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - ok
2875 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - ok
2876 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - start
2876 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - start
2876 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - ok
2876 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - start
2877 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - ok
2877 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - start
2877 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - ok
2877 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - ok
2878 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - start
2878 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - start
2878 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - ok
2878 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - ok
2879 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - start
2879 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - start
2879 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - ok
2879 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - ok
2880 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - start
2880 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - start
2880 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink value part - ok
2880 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Parse sink factory - ok
2881 [webcam-discovery-service] DEBUG com.github.eduramiba.webcamcapture.drivers.capturemanager.model.parser.CaptureManagerModelXMLParser  - Premature end of XML stream at root. Event type = 257
2897 [Thread-8] INFO com.github.sarxos.webcam.WebcamDiscoveryService  - Discovery will not run - driver CaptureManagerDriver does not support this feature
Selected camera is: FaceTime HD Camera
2902 [Thread-9] INFO com.github.sarxos.webcam.WebcamDiscoveryService  - Discovery will not run - driver CaptureManagerDriver does not support this feature
2903 [Thread-9] DEBUG com.github.sarxos.webcam.WebcamLock  - Lock Webcam FaceTime HD Camera
2930 [atomic-processor-1] INFO com.github.sarxos.webcam.ds.cgt.WebcamOpenTask  - Opening webcam FaceTime HD Camera
2949 [atomic-processor-1] INFO com.github.eduramiba.webcamcapture.drivers.capturemanager.CaptureManagerVideoDevice  - Using video media type: CaptureManagerMediaType{width=1280, height=720, majorType=MFMediaType_Video, subType=MFVideoFormat_YUY2}
3001 [atomic-processor-1] ERROR com.github.eduramiba.webcamcapture.drivers.capturemanager.CaptureManagerFrameGrabberSession  - Could not create session control last step
3002 [atomic-processor-1] ERROR com.github.eduramiba.webcamcapture.drivers.capturemanager.CaptureManagerFrameGrabberSession  - Call init before start!!
3005 [Thread-9] DEBUG com.github.sarxos.webcam.Webcam  - Webcam is now open FaceTime HD Camera`

**Comment by shadowwalkersteam** [comment]
I think this error "Could not create session control last step" is causing issue may be. But I don't understand the reason why its throwing this error. Any one have idea about this?

**Comment by eduramiba** [comment]
@shadowwalkersteam Not sure what could be the reason. But please make sure your camera is not already in use by any other application.

**Comment by shadowwalkersteam** [comment]
> @shadowwalkersteam Not sure what could be the reason. But please make sure your camera is not already in use by any other application.

no the camera is not in use by anyother app. the original java example of CaptureManager SDK working fine.

**Comment by shadowwalkersteam** [comment]
Do you have any idea what Dll’s are required by this media foundation based camera api?
I’ve already added those dll’s but I suspect something is missing. I also added vcruntime dlls too.

**Comment by eduramiba** [comment]
Hi @shadowwalkersteam the DLLs were recently updated, can you try again?

**Comment by eduramiba** [comment]
Does it work now?
