### ISSUE TITLE
Windows - First time it is streaming, if we close and reopen, it is not streaming

### ISSUE THREAD

**Issue by svcsrao** [eduramiba/webcam-capture-driver-native#7]
I have integrated this in Windows and Mac.

In Mac it is working perfect.
In Windows, First time when we open, it is streaming. If I close and reopen, it is not straming and displaying previously captured pic.

**Comment by pacioc193** [comment]
Same issue as #4 .
I forced in the main API to ignore that Webcam is already open.
If you need the snippet maybe i can find it

**Comment by eduramiba** [comment]
Duplicate of https://github.com/sarxos/webcam-capture/issues/859
